//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentService.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Link
    {
        public int LinkID { get; set; }
        public string LinkName { get; set; }
        public string LinkDescription { get; set; }
        public string LinkUse { get; set; }
        public string Link1 { get; set; }
        public string LinkPhoto { get; set; }
        public HttpPostedFileBase file { get; set; }
    }
}
