//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentService.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Material
    {
        public int MaterialNumber { get; set; }
        public string DepartmentCode { get; set; }
        public string CourseCode { get; set; }
        public Nullable<int> SectionNumber { get; set; }
        public string Semester { get; set; }
        public string Year { get; set; }
        public Nullable<int> LectureNumber { get; set; }
        public string LectureName { get; set; }
        public string PDF { get; set; }
        public HttpPostedFileBase file { get; set; }

        public virtual Section Section { get; set; }
    }
}
