//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskNumber { get; set; }
        public string DepartmentCode { get; set; }
        public string CourseCode { get; set; }
        public Nullable<int> SectionNumber { get; set; }
        public string Semester { get; set; }
        public string Year { get; set; }
        public string TaskHeader { get; set; }
        public string TaskDetails { get; set; }
        public string Type { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Type Type1 { get; set; }
    }
}
